---
# tasks file for packages

- name: Install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - software-properties-common

- name: Install pip in a way that does not break ansible
  easy_install: name=pip

- name: Check to see if docker is installed
  stat: path=/usr/bin/docker
  register: docker_exists

- name: Install docker via curl, ew
  shell: 'wget -qO- https://get.docker.com/ | sh'
  when: docker_exists.stat.exists == False


- name: Add ansible PPA
  apt_repository: repo='ppa:ansible/ansible' state=present

- name: Install ansible
  apt: name=ansible state=latest update_cache=yes

- name: Pip install docker package
  pip: name={{ item }} state=latest
  with_items:
    - docker-py
